name: movie_repository
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.4
  equatable: ^2.0.3
  json_annotation: ^4.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.1.1
  build_runner: ^2.1.4
  json_serializable: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
